# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  sln: '$(Build.SourcesDirectory)/docker-fixtures.sln'
  tests: '$(Build.SourcesDirectory)/src/Tests/DockerFixtures.Tests/DockerFixtures.Tests.csproj'
  artifacts: '$(Build.SourcesDirectory)/Artifacts'
  coverageResults: '$(artifacts)/Coverage/'

steps:
- script: dotnet build --configuration $(buildConfiguration) $(sln)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test $(tests) --logger "xunit;LogFileName=TestResults.xml" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
  displayName: 'dotnet test'
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '**/TestResults.xml'
  condition: always()
- script: |
    dotnet tool install dotnet-reportgenerator-globaltool --version 4.0.3 --tool-path .tools
    ./.tools/reportgenerator "-reports:$(Build.SourcesDirectory)/**/coverage.cobertura.xml" "-targetdir:$(coverageResults)" "-reporttypes:HtmlInline_AzurePipelines;HTMLChart;Cobertura"
  displayName: Generate code coverage report
- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage report
  enabled: true
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(coverageResults)/Cobertura.xml'
    reportDirectory: '$(coverageResults)'
    additionalCodeCoverageFiles: '$(coverageResults)/index.html'